package entidad;
// Generated 26-jun-2014 20:41:30 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name="contacto"
    ,catalog="bd"
)
public class Contacto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String direccion;
     private String telefono;
     private String correo;

    public Contacto() {
    }

    public Contacto(String nombre, String direccion, String telefono, String correo) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", length=50)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="correo", length=50)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


